const state={data:null,docs:[],brand:'all',category:'all',q:''};
const $=s=>document.querySelector(s);
const norm=s=>(s||'').toString().toLowerCase().replace(/[\s_./-]+/g,' ').trim();
const esc=s=>(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function highlight(text,q){if(!q)return esc(text);let out=esc(text);const parts=norm(q).split(' ').filter(x=>x.length>1).slice(0,6);for(const p of parts){const re=new RegExp(`(${p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'ig');out=out.replace(re,'<span class="match">$1</span>')}return out}
function fillFilters(){const brands=[...new Set(state.docs.map(x=>x.brand))].sort();$('#brand').innerHTML='<option value="all">전체 브랜드</option>'+brands.map(x=>`<option>${esc(x)}</option>`).join('');const cats=[...new Set(state.docs.flatMap(x=>x.categories||[]))].sort();$('#category').innerHTML='<option value="all">전체 밸브 종류</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('')}
function scoreDoc(d,tokens){if(!tokens.length)return 1;const title=norm(d.title),brand=norm(d.brand),models=norm((d.models||[]).join(' ')),specs=norm(Object.values(d.specs||{}).flat().join(' ')),all=norm(d.search_text);let score=0;for(const t of tokens){if(models.includes(t))score+=12;if(title.includes(t))score+=7;if(brand.includes(t))score+=5;if(specs.includes(t))score+=4;if(all.includes(t))score+=2;else return 0}return score}
function current(){const tokens=norm(state.q).split(' ').filter(Boolean);return state.docs.filter(d=>(state.brand==='all'||d.brand===state.brand)&&(state.category==='all'||(d.categories||[]).includes(state.category))).map(d=>({d,score:scoreDoc(d,tokens)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.d.brand.localeCompare(b.d.brand)).map(x=>x.d)}
function render(){const list=current();$('#count').textContent=list.length.toLocaleString();$('#grid').innerHTML=list.length?list.slice(0,500).map(d=>{const specs=Object.entries(d.specs||{}).flatMap(([k,v])=>(v||[]).slice(0,4).map(x=>`<span class="badge">${esc(x)}</span>`)).join('');const models=(d.models||[]).slice(0,8).map(x=>`<span class="badge model">${highlight(x,state.q)}</span>`).join('');return `<article class="card"><div class="cardhead"><div><div class="brand">${esc(d.brand)}</div><h3>${highlight(d.title,state.q)}</h3></div><span class="type">${esc((d.categories||['기타']).join(' · '))}</span></div><div class="badges">${models}${specs}</div><div class="excerpt">${highlight(d.excerpt||'',state.q)}</div><div class="actions"><a href="${esc(d.url)}" target="_blank" rel="noopener">공식 자료 열기 ↗</a></div></article>`}).join(''):`<div class="empty">검색 결과가 없어.<br>모델번호 일부, 브랜드명, <b>24V / 350bar / D03 / counterbalance</b> 같은 조건으로 다시 검색해봐.</div>`}
function bind(){$('#q').addEventListener('input',e=>{state.q=e.target.value;render()});$('#brand').addEventListener('change',e=>{state.brand=e.target.value;render()});$('#category').addEventListener('change',e=>{state.category=e.target.value;render()});document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{$('#q').value=c.dataset.q;state.q=c.dataset.q;render()});$('#reset').onclick=()=>{$('#q').value='';$('#brand').value='all';$('#category').value='all';state.q='';state.brand='all';state.category='all';render()}}
async function boot(){try{const r=await fetch('./data/catalog.json',{cache:'no-store'});state.data=await r.json();state.docs=state.data.documents||[];$('#brandCount').textContent=state.data.brand_count||0;$('#docCount').textContent=(state.data.document_count||0).toLocaleString();$('#updated').textContent=new Date(state.data.generated_at).toLocaleString('ko-KR');fillFilters();bind();render()}catch(e){$('#grid').innerHTML='<div class="empty">catalog.json을 읽지 못했어. GitHub Pages 또는 로컬 웹서버로 열어줘.</div>'}}
boot();
